INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (1, 601, 'General de Ley Personas Morales', 'No', 'Sí');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (2, 603, 'Personas Morales con Fines no Lucrativos', 'No', 'Sí');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (3, 605, 'Sueldos y Salarios e Ingresos Asimilados a Salarios', 'Sí', 'No');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (4, 606, 'Arrendamiento', 'Sí', 'No');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (5, 608, 'Demás ingresos', 'Sí', 'No');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (6, 609, 'Consolidación', 'No', 'Sí');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (7, 610, 'Residentes en el Extranjero sin Establecimiento Permanente en México', 'Sí', 'Sí');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (8, 611, 'Ingresos por Dividendos (socios y accionistas)', 'Sí', 'No');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (9, 612, 'Personas Físicas con Actividades Empresariales y Profesionales', 'Sí', 'No');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (10, 614, 'Ingresos por intereses', 'Sí', 'No', '12/11/2016', '');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (11, 616, 'Sin obligaciones fiscales', 'Sí', 'No', '12/11/2016', '');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (12, 620, 'Sociedades Cooperativas de Producción que optan por diferir sus ingresos', 'No', 'Sí');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (13, 621, 'Incorporación Fiscal', 'Sí', 'No', '12/11/2016', '');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (14, 622, 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras', 'Sí', 'Sí');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (15, 623, 'Opcional para Grupos de Sociedades', 'No', 'Sí');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (16, 624, 'Coordinados', 'No', 'Sí');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (17, 628, 'Hidrocarburos', 'No', 'Sí');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (18, 607, 'Régimen de Enajenación o Adquisición de Bienes', 'No', 'Sí');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (19, 629, 'De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales', 'Sí', 'No');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (20, 630, 'Enajenación de acciones en bolsa de valores', 'Sí', 'No');
INSERT INTO RegimenFiscal (ID, CodigoRegimen, Descripcion, AplicaFisica, AplicaMoral) VALUES (21, 615, 'Régimen de los ingresos por obtención de premios', 'Sí', 'No');